### ISSUE TITLE
Applications menu: Error for extension point conflict

### ISSUE THREAD

**Issue by chenkangyang** [gcampax/gnome-shell-extensions#17]
1. Alt + F2
2. Type lg
3. Click 'Extensions'
4. 'Show errors' below Application Menu
Then the error is:
Error: extension point conflict: there is already a status indicator for role apps-menu

how to fix it ?

**Comment by gcampax** [comment]
Hi, thanks for your report. This is not the upstream repository for this package, and I'm not actively working on this. You should file your issue at https://gitlab.gnome.org/GNOME/gnome-shell-extensions/
